export const TauriCommand = {
  AcknowledgeQuit: "acknowledge_quit",
  AttachmentStatus: "attachment_status",
  BackupNow: "backup_now",
  ConfigureBackup: "configure_backup",
  CancelResearchProcess: "cancel_research_process",
  CaptureClipboardImage: "capture_clipboard_image",
  CheckpointBackupStatus: "checkpoint_backup_status",
  ClaudeCliDefaults: "claude_cli_defaults",
  ClaudeSetupStatus: "claude_setup_status",
  ClearDraft: "clear_draft",
  CreateTidbit: "create_tidbit",
  DeleteTidbit: "delete_tidbit",
  DrillBackupRestore: "drill_backup_restore",
  DiscardFileDropSelections: "discard_file_drop_selections",
  DismissQuickAdd: "dismiss_quick_add",
  EditTidbit: "edit_tidbit",
  ImageOcrDiagnostics: "image_ocr_diagnostics",
  ImageStatus: "image_status",
  IngestClipboardImage: "ingest_clipboard_image",
  IngestDroppedImages: "ingest_dropped_images",
  IngestSelectedAttachment: "ingest_selected_attachment",
  IngestSelectedImage: "ingest_selected_image",
  IngestSelectedPdf: "ingest_selected_pdf",
  ListResearchRuns: "list_research_runs",
  ListBackupCheckpoints: "list_backup_checkpoints",
  ListTidbitRevisions: "list_tidbit_revisions",
  ListTidbits: "list_tidbits",
  LoadDraft: "load_draft",
  LoadBackupSettings: "load_backup_settings",
  LoadMaintenanceDiagnostics: "load_maintenance_diagnostics",
  LoadResearchRun: "load_research_run",
  LoadShortcutSettings: "load_shortcut_settings",
  LoadTidbit: "load_tidbit",
  LoadTidbitRevision: "load_tidbit_revision",
  MaintainMedia: "maintain_media",
  MediaIntegrityScan: "media_integrity_scan",
  MediaLimits: "media_limits",
  OpenAttachmentExternal: "open_attachment_external",
  OpenPdfExternal: "open_pdf_external",
  OpenSourceUrl: "open_source_url",
  PrepareUpdateRelaunch: "prepare_update_relaunch",
  PassageEmbeddingIndexStatus: "passage_embedding_index_status",
  PdfStatus: "pdf_status",
  PrepareSemanticRuntime: "prepare_semantic_runtime",
  PreviewBackupRestore: "preview_backup_restore",
  PurgeTidbit: "purge_tidbit",
  RebuildEmbeddingIndex: "rebuild_embedding_index",
  RebuildSearchIndexes: "rebuild_search_indexes",
  ReclaimEligibleMedia: "reclaim_eligible_media",
  RepairSemanticRuntime: "repair_semantic_runtime",
  RerunResearchProcess: "rerun_research_process",
  ResolveCitation: "resolve_citation",
  RestoreTidbit: "restore_tidbit",
  RetryFailedExtractions: "retry_failed_extractions",
  RetryImageOcr: "retry_image_ocr",
  RetryPdfExtraction: "retry_pdf_extraction",
  RetrySemanticRuntime: "retry_semantic_runtime",
  RevealAttachmentInFinder: "reveal_attachment_in_finder",
  RunIntegrityCheck: "run_integrity_check",
  RuntimeProbe: "runtime_probe",
  SaveDraft: "save_draft",
  SaveResearchAnswerAsTidbit: "save_research_answer_as_tidbit",
  SearchPassages: "search_passages",
  SelectAttachment: "select_attachment",
  SelectImage: "select_image",
  SelectPdf: "select_pdf",
  SemanticRuntimeLogs: "semantic_runtime_logs",
  SemanticRuntimeStatus: "semantic_runtime_status",
  SetFileDropConsumerActive: "set_file_drop_consumer_active",
  SetBackupEnabled: "set_backup_enabled",
  SetAutomaticUpdateChecks: "set_automatic_update_checks",
  SetQuickAddFileDialogOpen: "set_quick_add_file_dialog_open",
  SetShortcutSettings: "set_shortcut_settings",
  ShowMain: "show_main",
  ShowQuickAdd: "show_quick_add",
  StartResearchProcess: "start_research_process",
  TakeOverBackup: "take_over_backup",
  TestBackupConnection: "test_backup_connection",
} as const;

export const TauriEvent = {
  CheckForUpdates: "kosh://check-for-updates",
  FileDrop: "kosh://file-drop",
  OpenSettings: "kosh://open-settings",
  PrepareQuit: "kosh://prepare-quit",
  QuickAddShown: "kosh://quick-add-shown",
  QuitCanceled: "kosh://quit-canceled",
  ResearchProcess: "kosh://research-process",
  ShortcutSettingsChanged: "kosh://shortcut-settings-changed",
  StartupSmokeReady: "kosh://startup-smoke-ready",
} as const;

export const TauriWindow = {
  Main: "main",
  QuickAdd: "quick-add",
} as const;

export type TauriCommandName = (typeof TauriCommand)[keyof typeof TauriCommand];
export type TauriEventName = (typeof TauriEvent)[keyof typeof TauriEvent];
export type TauriWindowName = (typeof TauriWindow)[keyof typeof TauriWindow];
