export const TauriCommand = {
  AcknowledgeQuit: "acknowledge_quit",
  AttachmentStatus: "attachment_status",
  BackupNow: "backup_now",
  CancelUpdateRelaunch: "cancel_update_relaunch",
  ConfigureBackup: "configure_backup",
  CaptureClipboardImage: "capture_clipboard_image",
  CheckpointBackupStatus: "checkpoint_backup_status",
  CheckpointWorkingCopy: "checkpoint_working_copy",
  DeleteTidbit: "delete_tidbit",
  DiscardWorkingCopy: "discard_working_copy",
  DrillBackupRestore: "drill_backup_restore",
  DiscardFileDropSelections: "discard_file_drop_selections",
  CopyText: "copy_text",
  ImageOcrDiagnostics: "image_ocr_diagnostics",
  ImageStatus: "image_status",
  IngestClipboardImage: "ingest_clipboard_image",
  IngestDroppedImages: "ingest_dropped_images",
  IngestSelectedAttachment: "ingest_selected_attachment",
  IngestSelectedImage: "ingest_selected_image",
  IngestSelectedPdf: "ingest_selected_pdf",
  ListBackupCheckpoints: "list_backup_checkpoints",
  ListWorkingCopies: "list_working_copies",
  LoadBackupSettings: "load_backup_settings",
  LoadMaintenanceDiagnostics: "load_maintenance_diagnostics",
  LoadShortcutSettings: "load_shortcut_settings",
  LoadTidbit: "load_tidbit",
  LoadWorkingCopy: "load_working_copy",
  MaintainMedia: "maintain_media",
  MediaIntegrityScan: "media_integrity_scan",
  MediaLimits: "media_limits",
  OpenAttachmentExternal: "open_attachment_external",
  OpenPdfExternal: "open_pdf_external",
  OpenSourceUrl: "open_source_url",
  PrepareUpdateRelaunch: "prepare_update_relaunch",
  ReserveWorkingCopyForMedia: "reserve_working_copy_for_media",
  PassageEmbeddingIndexStatus: "passage_embedding_index_status",
  PdfStatus: "pdf_status",
  PrepareSemanticRuntime: "prepare_semantic_runtime",
  PreviewBackupRestore: "preview_backup_restore",
  RebuildEmbeddingIndex: "rebuild_embedding_index",
  RebuildSearchIndexes: "rebuild_search_indexes",
  ReclaimEligibleMedia: "reclaim_eligible_media",
  RepairSemanticRuntime: "repair_semantic_runtime",
  ResolveCitation: "resolve_citation",
  RestoreTidbit: "restore_tidbit",
  RetryFailedExtractions: "retry_failed_extractions",
  RetryImageOcr: "retry_image_ocr",
  RetryPdfExtraction: "retry_pdf_extraction",
  RetrySemanticRuntime: "retry_semantic_runtime",
  RevealAttachmentInFinder: "reveal_attachment_in_finder",
  RunIntegrityCheck: "run_integrity_check",
  RuntimeProbe: "runtime_probe",
  SaveWorkingCopy: "save_working_copy",
  SearchPassages: "search_passages",
  SelectAttachment: "select_attachment",
  SelectImage: "select_image",
  SelectPdf: "select_pdf",
  SemanticRuntimeLogs: "semantic_runtime_logs",
  SemanticRuntimeStatus: "semantic_runtime_status",
  SetFileDropConsumerActive: "set_file_drop_consumer_active",
  SetBackupEnabled: "set_backup_enabled",
  SetAutomaticUpdateChecks: "set_automatic_update_checks",
  SetShortcutSettings: "set_shortcut_settings",
  ShowMain: "show_main",
  TakeOverBackup: "take_over_backup",
  TestBackupConnection: "test_backup_connection",
} as const;

export const TauriEvent = {
  CheckForUpdates: "kosh://check-for-updates",
  FileDrop: "kosh://file-drop",
  NavigationCommand: "kosh://navigation-command",
  OpenSettings: "kosh://open-settings",
  PrepareQuit: "kosh://prepare-quit",
  QuitCanceled: "kosh://quit-canceled",
  ShortcutSettingsChanged: "kosh://shortcut-settings-changed",
  StartupSmokeReady: "kosh://startup-smoke-ready",
} as const;

export const TauriWindow = {
  Main: "main",
} as const;

export type TauriCommandName = (typeof TauriCommand)[keyof typeof TauriCommand];
export type TauriEventName = (typeof TauriEvent)[keyof typeof TauriEvent];
export type TauriWindowName = (typeof TauriWindow)[keyof typeof TauriWindow];
